---
env:
  browser: true
  es2021: true
  jquery: true
  node: true
extends: 'eslint:recommended'
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
  requireConfigFile: false
rules: { }
